### ISSUE TITLE
bug: ardupilot-manager: ArduCopter failing to fetch for Navigator

### ISSUE THREAD

**Issue by ES-Alexander** [bluerobotics/BlueOS-docker#1153]
### Bug description

Navigator firmwares are fetching fine, except for Copter. The https://firmware.ardupilot.org/Copter/stable-4.2.3/navigator/ webpage loads fine, so not sure why the fetch is failing.

[logfile_09-20-2022_00_34_19.log](https://github.com/bluerobotics/BlueOS-docker/files/9603115/logfile_09-20-2022_00_34_19.log)

### Steps to reproduce

1. Connect Navigator
2. Open General page
3. Try to fetch Copter firmware -> fails
4. Try to fetch other vehicle type (Sub/Plane/Rover) -> succeeds

### Primary pain point(s)

Requires people wanting to use ArduCopter to do a manual upload, which is more complicated and less intuitive than the normal simple installation process.

### Prerequisites

- [X] I have checked to make sure that a similar request has not already been filed or fixed.

**Comment by rafaellehmkuhl** [comment]
This is happening because [there are multiple candidates for download](https://firmware.ardupilot.org/Copter/beta/),`navigator` and `navigator-heli`, [different from Sub](https://firmware.ardupilot.org/Sub/beta/), for example.

![image](https://user-images.githubusercontent.com/6551040/196272619-3e23e20e-96a9-4f13-9d5d-9bcd8c3a4e46.png)

I will work on a workaround for this.

**Comment by rafaellehmkuhl** [comment]
![image](https://user-images.githubusercontent.com/6551040/196307058-0e77dff1-6a87-4363-812c-c8b5db9ca1dd.png)

Proof of fix.
