### ISSUE TITLE
Video manager dies

### ISSUE THREAD

**Issue by rafaellehmkuhl** [bluerobotics/BlueOS-docker#1556]
I had two streams working (BR camera and fake ball), was using then with Cockpit and suddenly the video manager died.
Following is the log:
[mavlink-camera-manager.log.2023-03-21.zip](https://github.com/bluerobotics/BlueOS-docker/files/11034950/mavlink-camera-manager.log.2023-03-21.zip)

@patrickelectric @joaoantoniocardoso this probably interest you guys

**Comment by rafaellehmkuhl** [comment]
PS: restarting the service makes it work again (with the streams restored).

**Comment by joaoantoniocardoso** [comment]
Thanks @rafaellehmkuhl, I analyzed the log and almost certainly it's the same problem I've been working on.

To keep everybody updated, after many hours and several small fixes along the way, yesterday I finally understood the root cause of that point of failure. Tomorrow I'll be submitting the PRs to the MCM's repository, then probably at the beginning of the next week, releasing a new version, and then creating a PR here to update it, as usual.
