### ISSUE TITLE
mavlink-camera-manager cpu usage is higher on latest master

### ISSUE THREAD

**Issue by Williangalvani** [bluerobotics/BlueOS-docker#1627]
Both when running an rtsp stream

Beta 16:
![image](https://user-images.githubusercontent.com/4013804/233461959-c808f294-aa9b-4bb7-9b97-7629b3a5441a.png)

Master:
![image](https://user-images.githubusercontent.com/4013804/233462879-7bfedb55-1f2f-492c-a2ff-71895c208693.png)

I've seen master at 140% cpu usage, but I'm unable to replicate.

**Comment by patrickelectric** [comment]
maybe related with https://github.com/bluerobotics/mavlink-camera-manager/issues/215 ?
@joaoantoniocardoso

**Comment by joaoantoniocardoso** [comment]
> maybe related with [bluerobotics/mavlink-camera-manager#215](https://github.com/bluerobotics/mavlink-camera-manager/issues/215) ? @joaoantoniocardoso

unrelated to that, possibly related to (a) thumbnails or (b) proxies.

@Williangalvani was you with BlueOS' video page opened?

**Comment by Williangalvani** [comment]
> So that's probably (b) proxies. I'd need to confirm with tests, but that's really bad news

what do you mean by proxies? inside mcm?

**Comment by joaoantoniocardoso** [comment]
From your graphs I see two interesting things:
- higher jitter in delivered frame rate, with huge dips, which are freezings
- doubled the CPU usage

Probably the higher CPU is causing the freezings, which doesn't seem to be related to the thumbnail system.

---

Just started an investigation here... Looking for causes for that higher CPU usage. Beta16 uses MCM t3.10.1 ([diff](https://github.com/bluerobotics/mavlink-camera-manager/compare/t3.10.1...t3.11.3))

From that diff, I found only three possible related changes:
- [using proxysrc/proxyxsink pair to split each sink into a different pipeline (UDP and ImageSInk only) 
](https://github.com/bluerobotics/mavlink-camera-manager/compare/t3.10.1...t3.11.3#diff-2f1f6625bb4a423e0d90240558d364879a8032f93f342a9b65b2321432752869R15-R16)
- [no more fixating the profile](https://github.com/bluerobotics/mavlink-camera-manager/compare/t3.10.1...t3.11.3#diff-aba234205cda9893ce54b18bd8e05da0a3c73b9bc0afc514f3ab7a4ad0c61025R57)
- [pipeline runner now runs on in tokio green thread instead of in an OS thread](https://github.com/bluerobotics/mavlink-camera-manager/compare/t3.10.1...t3.11.3#diff-c9de2f4f0f6a1630959cbe0944fc9a1ae9e1c20d6d01a32faf0c28b5f1a2cc68R139)

Obviously, splitting means more pipelines, more threads, and more overhead, but it's probably something heavier than that happening on the GStreamer side. I'd try to replicate and investigate it further.

**Comment by joaoantoniocardoso** [comment]
![image](https://user-images.githubusercontent.com/5920286/234095061-bea69f15-252c-41d3-99ec-ae7e35ea4056.png)

This queue4 is the one that connects the Tee from the v4l source pipeline with the webrtcbin

**Comment by joaoantoniocardoso** [comment]
We have a clue here, after running for some time:

![image](https://user-images.githubusercontent.com/5920286/234101449-3e661adb-475c-430d-b306-80db09c59ddb.png)

**Comment by joaoantoniocardoso** [comment]
:facepalm: `current-level-time=992125648` means it's holding almost 1 second of data. To make it stateless I should also set `max-size-time=0`. I'd already noticed that when working on the RTSP to WebRTC, so a Patch is on the way...

**Comment by joaoantoniocardoso** [comment]
Turns out that the problem was something completely different: an integration in a logging library, anyways, it's fixed now :)
