### ISSUE TITLE
core: Add always-available wifi hotspot

### ISSUE THREAD

**Issue by patrickelectric** [bluerobotics/BlueOS-docker#307]

**Comment by rafaellehmkuhl** [comment]
Cool. I have the PR for this one almost ready, using hostapd. Can deliver next week.

**Comment by patrickelectric** [comment]
Any update on that ?

**Comment by rafaellehmkuhl** [comment]
The branch is working but we deprioritized as its not on the current roadmap. There are some wifi/hotspot enable-disable tests to do yet.

**Comment by rafaellehmkuhl** [comment]
Reading a little more about IoT solutions, I came to the opinion that we should have an always-available wifi hotspot, instead of one that is available only when there no client-connection. This makes everything easier and more intuitive to the user (companion hotspot will always be there). For this to work, the raspberry wlan physical interface needs support for virtual-wlan, which it does.

Implementing this demands a little more work but will certainly pay off in terms of user experience.

More information (including implementation) can be found on the following links:

- https://github.com/lukicdarkoo/rpi-wifi
- https://thepi.io/how-to-use-your-raspberry-pi-as-a-wireless-access-point/
- https://blog.ithasu.org/2017/11/raspberry-pi-0w-as-both-wifi-client-and-access-point/
- https://blog.thewalr.us/2017/09/26/raspberry-pi-zero-w-simultaneous-ap-and-managed-mode-wifi/
- https://imti.co/iot-wifi/
- https://www.0xf8.org/2016/02/using-your-raspberry-pi-zeros-usb-wifi-adapter-as-both-wifi-client-and-access-point/

**Comment by patrickelectric** [comment]
The wifi name should be unique per vehicle.

**Comment by rafaellehmkuhl** [comment]
> The wifi name should be unique per vehicle. 

That would be interesting. Will add.

You mean being configurable by the user or by using a part-random name?

I'm a fan of both, but the first already solves the problem so will use that for now.
