### ISSUE TITLE
bug: Rov lost static ip address setting in latest master

### ISSUE THREAD

**Issue by Williangalvani** [bluerobotics/BlueOS-docker#831]
### Bug description

it used to have 192.168.2.2 as a fixed IP. after the last update I did, it doesn't

### Steps to reproduce

- start in beta12 (13?)
- update to master
- ip should be gone.

### Primary pain point(s)

this means the user has no access to the rov unless it is connected to a wifi network.

### Prerequisites

- [X] I have checked to make sure that a similar request has not already been filed or fixed.

**Comment by rafaellehmkuhl** [comment]
Can you upload the cable-guy log? We should know what happened from there.

**Comment by Williangalvani** [comment]
I'll try to replicate it soon, I no longer have the logs

**Comment by patrickelectric** [comment]
I'm unable to replicate it here

**Comment by rafaellehmkuhl** [comment]
> I'm unable to replicate it here

Same

**Comment by rafaellehmkuhl** [comment]
Even though we were not able to replicate the issue, if it indeed happened, I believe it was because of a change on the cable-guy base structure (from supporting one IP to supporting many IPs).

Anyway, since we demanded a fresh flash on Beta16/1.0.0, I believe this becomes a non-issue and we can close it.

What do you think, @Williangalvani ?

**Comment by Williangalvani** [comment]
Agreed
